from typing import Protocol


class MT5ClientProtocol(Protocol):
    @property
    def demo_trade_mode(self) -> int: ...

    def initialize(
        self,
        path: str | None,
        *,
        login: int,
        password: str,
        server: str,
        timeout: int,
    ) -> bool: ...

    def shutdown(self) -> None: ...

    def last_error(self) -> tuple[int, str]: ...

    def account_info(self) -> object | None: ...

    def terminal_info(self) -> object | None: ...

    def symbol_info(self, symbol: str) -> object | None: ...

    def symbol_select(self, symbol: str, enable: bool) -> bool: ...

    def symbol_info_tick(self, symbol: str) -> object | None: ...

    def timeframe_value(self, timeframe: str) -> int: ...

    def copy_rates_from(
        self, symbol: str, timeframe: int, end_time: object, count: int
    ) -> object | None: ...

    def copy_rates_range(
        self, symbol: str, timeframe: int, start_time: object, end_time: object
    ) -> object | None: ...


    @property
    def trade_action_deal(self) -> int: ...

    @property
    def trade_action_sltp(self) -> int: ...

    @property
    def trade_action_remove(self) -> int: ...

    def order_type(self, direction: str) -> int: ...

    def filling_mode_from_symbol(self, filling_mode: int) -> int: ...

    def trade_check_accepted(self, retcode: int) -> bool: ...

    def trade_outcome(self, retcode: int) -> str: ...

    def position_direction(self, position_type: int) -> str: ...

    def deal_direction(self, deal_type: int) -> str: ...

    def order_check(self, request: dict[str, object]) -> object | None: ...

    def order_calc_margin(
        self, order_type: int, symbol: str, volume: float, price: float
    ) -> float | None: ...

    def order_send(self, request: dict[str, object]) -> object | None: ...

    def positions_get(self, **kwargs: object) -> object | None: ...

    def orders_get(self, **kwargs: object) -> object | None: ...

    def history_deals_get(self, *args: object, **kwargs: object) -> object | None: ...

    def history_orders_get(self, *args: object, **kwargs: object) -> object | None: ...

    def symbol_trading_allowed(self, trade_mode: int) -> bool: ...
