from __future__ import annotations

from collections.abc import Awaitable, Callable
from datetime import datetime, timezone
import math
from typing import Any
from uuid import uuid4

from sqlalchemy import select
from sqlalchemy.ext.asyncio import AsyncSession, async_sessionmaker

from app.analysis.repository import SignalRepository
from app.database.models.risk import TradePlan
from app.database.models.signal import Signal
from app.demo.exceptions import DemoValidationError
from app.mt5.exceptions import MT5Error

DEVELOPMENT_TESTING_STRATEGY = "DEVELOPMENT_TESTING_MODE"
MarketSnapshot = Callable[[str | None], Awaitable[dict[str, Any]]]


class SyntheticSignalService:
    def __init__(
        self,
        repository: SignalRepository,
        symbol: str,
        snapshot: MarketSnapshot | None = None,
        clock: Callable[[], datetime] | None = None,
    ) -> None:
        configured_symbol = symbol.strip()
        if not configured_symbol or len(configured_symbol) > 32:
            raise ValueError("Testing symbol is invalid")
        self._repository = repository
        self._configured_symbol = configured_symbol
        self._snapshot = snapshot
        self._clock = clock or (lambda: datetime.now(timezone.utc))

    async def create(self, direction: str) -> dict[str, Any]:
        if direction not in {"BUY", "SELL"}:
            raise ValueError("Testing direction must be BUY or SELL")
        observed_at = self._clock()
        symbol, reference_price = await self._market_reference(direction)
        values = {
            "signal_id": str(uuid4()),
            "symbol": symbol,
            "direction": direction,
            "strategy_name": DEVELOPMENT_TESTING_STRATEGY,
            "timeframe": "H1/M15/M5",
            "entry_reference_price": reference_price,
            "atr": 2.0,
            "confidence_score": 100.0,
            "reasons": ["Synthetic candidate generated by development testing mode"],
            "rejection_reasons": [],
            "score_factors": [{
                "factor": DEVELOPMENT_TESTING_STRATEGY,
                "passed": True,
                "weight": 100,
                "points": 100,
            }],
            "candle_time": observed_at,
            "created_at": observed_at,
            "status": "CANDIDATE",
        }
        return await self._repository.save_or_get_existing(values)

    async def _market_reference(self, direction: str) -> tuple[str, float]:
        if self._snapshot is None:
            return self._configured_symbol, 3000.0
        try:
            snapshot = await self._snapshot(self._configured_symbol)
            symbol = str(snapshot["symbol"]["name"]).strip()
            price = float(snapshot["tick"]["ask" if direction == "BUY" else "bid"])
            if not symbol or len(symbol) > 32 or not math.isfinite(price) or price <= 0:
                raise ValueError("Active MT5 market reference is invalid")
            return symbol, price
        except (MT5Error, KeyError, TypeError, ValueError):
            return self._configured_symbol, 3000.0


class SyntheticSignalPolicy:
    def __init__(self, sessions: async_sessionmaker[AsyncSession]) -> None:
        self._sessions = sessions

    async def is_testing_trade_plan(self, trade_plan_id: str) -> bool:
        async with self._sessions() as session:
            statement = (
                select(Signal.signal_id)
                .join(TradePlan, TradePlan.signal_id == Signal.signal_id)
                .where(
                    TradePlan.trade_plan_id == trade_plan_id,
                    Signal.strategy_name == DEVELOPMENT_TESTING_STRATEGY,
                )
            )
            return await session.scalar(statement) is not None


class ProductionDemoTestingGuard:
    def __init__(self, delegate: Any, policy: SyntheticSignalPolicy) -> None:
        self._delegate = delegate
        self._policy = policy

    async def execute(
        self, trade_plan_id: str, idempotency_key: str
    ) -> dict[str, Any]:
        if await self._policy.is_testing_trade_plan(trade_plan_id):
            raise DemoValidationError(
                "Development testing signals cannot be executed in production"
            )
        return await self._delegate.execute(trade_plan_id, idempotency_key)

    def __getattr__(self, name: str) -> Any:
        return getattr(self._delegate, name)
